import { ms } from 'react-native-size-matters';
import { sfs } from '../../utils/responsibleText';

export default {
  Sizes: {
    FONTSIZE_BUTTON: sfs(8),
    FONTSIZE_BUTTON_SEND: sfs(12),
    FONTSIZE_BUTTON_TITLE: sfs(20),
    ICON_SIZE_BUTTON: sfs(15),
    FONTSIZE_TITLE: sfs(22),
    FONTSIZE_LABEL: sfs(12),
    FONTSIZE_INPUT_LABEL: sfs(13),
    FONTSIZE_INPUT: sfs(20),
    ICON_SIZE: ms(22),
    FONTSIZE_SUBTITLE: sfs(12),
  },

  Colors: {
    BLACK: '#000',
    WHITE: '#FFF',
    GRAY: '#333',
    FONT_INPUT: '#444444',
    MEDIUM_GRAY: '#666',
    LIGHT_GRAY: '#EEE',
    GRANITE: '#c8c9c7',
    ERROR: '#C12126',
    FEEDBACK_CORRECT: '#6ea204',
    FEEDBACK_WARNING: '#F2AF00',
    BACKGROUND_WHITE: '#fafafa',
    GRAY_LIGHT: '#bbbbbb',
    SECONDARY_LIGHT_GRAY: '#b4b4b4',
    CARD_TEXT: '#707070',
    BORDER_BLACK: '#0000001A',
    SECONDARY_MEDIUM_GRAY: '#848484',
    COLOR_APLICATION: '#FFFFFF',
    SOFT_BLACK: '#161616',
    GREY: '#C2C2C2',
    SOFT_GREY: '#F6F6F6',
    PINK: '#FA81AC',
    PURPLE: '#5D5B7E',
    DARK_PURPLE: '#34325E',
    BACKGROUND: '#FFFFFF',
    BORDER: '#FA81AC',
    BUTTON_TEXT: '#FFF',
    DEFAULT_FONT: '#121212',
    BUTTON_BACKGROUND: '#FA81AC',
    SUBTITLE: '#eba83a',
    TITLE_FONT: '#dc9116',
    FONT_HOME: '#121212',
    INPUT_COLOR: '#BB371A',
    BORDER_PROFILE: '#C2C2C2',
    BACKGROUND_INPUT: '#F6F6F6',
    BORDER_SEARCH: '#F6F6F6',
    BACKGROUND_MODAL: '#FAFAFA',
    TEXT_CLICKABLE: '#333',
    BUTTON_CANCEL: '#C12126',
    SHOW_BUTTON: '#0645AD',
  },
};

// export default {
//   Colors: {
//     BLACK: '#000',
//     SOFT_BLACK: '#161616',
//     GREY: '#C2C2C2',
//     SOFT_GREY: '#F6F6F6',
//     WHITE: '#FFF',
//     PINK: '#FA81AC',
//     PURPLE: '#5D5B7E',
//     DARK_PURPLE: '#34325E',
//   },
//   Sizes: {
//     FONTSIZE_TITLE: sfs(36),
//     FONTSIZE_SUBTITLE: sfs(12),
//     FONTSIZE_BUTTON_TITLE: sfs(12),
//     FONTSIZE_INPUT: sfs(14),
//     FONTSIZE_INPUT_LABEL: sfs(15),
//     ICON_SIZE: ms(22),
//   },
// };
